"""Add auth and domain models

Revision ID: 141600d61ada
Revises: b63814d7e04f
Create Date: 2026-07-17 17:45:37.614521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141600d61ada'
down_revision: Union[str, None] = 'b63814d7e04f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('urls', sa.Column('domain_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'urls', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'urls', 'domains', ['domain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'urls', type_='foreignkey')
    op.drop_constraint(None, 'urls', type_='foreignkey')
    op.drop_column('urls', 'domain_id')
    op.drop_column('urls', 'user_id')
    # ### end Alembic commands ###
